### ISSUE TITLE
MSVD dataset

### ISSUE THREAD

**Issue by sharontaozi** [niluthpol/multimodal_vtt#11]
Recently, I extracted the features of MSVD myself and put it into this model for testing, but the results are very different, so I would like to ask if there is an error in the method of extracting features.
First,I extracted a key frame for every 5 frames.
Second,I used resnet-152 to extract features,and extracted 2048-dimensional features from the last global average pooling layer.
Third,I mean the output of each frame as a features of the video.

Here is my code：

def Resnet152():
    # load pretrained model
    resnet152 = models.resnet152(pretrained=True)
    # remove the last layer
    modules=list(resnet152.children())[:-1]
    resnet152=nn.Sequential(*modules)
    for p in resnet152.parameters():
        p.requires_grad = False
    resnet152.cuda()
    return resnet152

def extract_feature(model,imgpath):
    model.eval()		
    img=Image.open(imgpath)
    img=img.resize((TARGET_IMG_SIZE, TARGET_IMG_SIZE))
    tensor=img_to_tensor(img)
    tensor=tensor.resize_(1,3,224,224)
    tensor=tensor.cuda()	
    result=model(Variable(tensor))
    result_npy=result.data.cpu().numpy()	
    return result_npy[0]

def each_feature(frame_path):
    model=Resnet152()
    tmp = extract_feature(model, frame_path)
    tmp=tmp.flatten()
    return tmp

Would you like to give me some suggestions? Would you like to share the features of MSVD?

**Comment by niluthpol** [comment]
I have used Caffe for ResNet feature extraction. I have shared features in https://drive.google.com/drive/folders/1fWZRtCN1pXBVsRViPUGWLKl1On18LI76?usp=sharing

**Comment by sharontaozi** [comment]
Thank you! appreciate！

**Comment by sharontaozi** [comment]
Hello,Thank you for your features.
    And I have an another question.What's the different between "Result using Partition used by JMET and JMDV"and "Result using Partition used by LJRV"? What's more,I put your features into your model,but the result is bad.V2T(using resnet features):R@1 just 9.6,R@5 just 20.5 R@10 just 30.1 . If my caption is not good?
    When I processed the caption,I found five different descriptions from the captions of each video.Is the operation wrong?
  
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Niluthpol Chowdhury Mithun"<notifications@github.com>;
 发送时间: 2019年6月9日(星期天) 下午4:01
 收件人: "niluthpol/multimodal_vtt"<multimodal_vtt@noreply.github.com>;
 抄送: "sharon桃子"<499400402@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [niluthpol/multimodal_vtt] MSVD dataset (#11)

 

 
I have used Caffe for ResNet feature extraction. I have shared features in https://drive.google.com/drive/folders/1fWZRtCN1pXBVsRViPUGWLKl1On18LI76?usp=sharing

**Comment by niluthpol** [comment]
LJRV Partition: Randomly chosen 5 ground-truth sentences were used.  JMET and JMDV Partitions: These papers use all ground-truth English sentences (In MSVD, most images have around 15 or more ground-truth sentences).

**Comment by sharontaozi** [comment]
Hello,
     I want to use the LJRV method, so I tried the following steps:
1. Select the first 5 sentences for each video as a description
2, form a dictionary
3, according to the dictionary form train_caption.pkl\train_caption.pkl\train_caption.pkl. The file format is consistent with the format of capsule.pkl of msr_vtt
 And then I put the caption.pkl into your model,but the result was not good.As the picture shows:
  


     Is there any problem with my operation?
 

 ------------------ 原始邮件 ------------------
  发件人: "Niluthpol Chowdhury Mithun"<notifications@github.com>;
 发送时间: 2019年6月10日(星期一) 凌晨0:20
 收件人: "niluthpol/multimodal_vtt"<multimodal_vtt@noreply.github.com>;
 抄送: "sharon桃子"<499400402@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [niluthpol/multimodal_vtt] MSVD dataset (#11)

 

 
LJRV Partition: Randomly chosen 5 ground-truth sentences were used. JMET and JMDV Partitions: These papers use all ground-truth English sentences (In MSVD, most images have around 15 or more ground-truth sentences).

**Comment by czy-orange** [comment]
> I have used Caffe for ResNet feature extraction. I have shared features in https://drive.google.com/drive/folders/1fWZRtCN1pXBVsRViPUGWLKl1On18LI76?usp=sharing

Thanks for your sharing! BTW, which resnet did you use to extract features(ResNet152 or resnet of other depth)?
