### ISSUE TITLE
the features about MSVD

### ISSUE THREAD

**Issue by xixiareone** [niluthpol/multimodal_vtt#18]
I am very interested in your work. Can you share the I3D features of MSVD, without the operation of average pooling, only the original features of I3D.

**Comment by AliceShen122** [comment]
i need it too. thank you!

**Comment by niluthpol** [comment]
Thanks for the interest! You can find the features in this link: https://drive.google.com/drive/folders/1QQ5nkUb2yhm0RIjIKXKWskFdEBNygP3D?usp=sharing

**Comment by xixiareone** [comment]
Can you share the features after layer4 in I3D-backbone instead of the features after going through the fully connected layer.

Many thanks!

**Comment by niluthpol** [comment]
Sorry. I do not have that saved.

**Comment by xixiareone** [comment]
Can you share the pretrained model about extracting the msvd features？I try to extract by myself.
Thank you very much！



---Original---

**Comment by niluthpol** [comment]
Please follow deepmind kinetics-i3d repo for i3d feature extraction. https://github.com/deepmind/kinetics-i3d
