### ISSUE TITLE
Video-caption pairs' number of `msvd_captions_test.pkl` in `all` dir is strange

### ISSUE THREAD

**Issue by jianjieluo** [niluthpol/multimodal_vtt#19]
hi, 

I check the [`msvd_captions_test.pkl`](https://drive.google.com/file/d/1UpG7drSrtmXpM0MfvFPOdBRFLAp_yf7L/view?usp=sharing) in `15` dir and it contains 10050 video-text pairs from 670 test videos with 15 sentences per video, which makes sense, while I find that the [`msvd_captions_test.pkl`](https://drive.google.com/file/d/1fkF9cj-MjE89q6Ks173t2l8FpngjGWXC/view?usp=sharing) in `all` dir contains only 11105 video-text pairs and 651 video ids rather than 670 as the S2VT split. Why?

I have also checked the original msvd caption annotations and get 27735 video-text pairs from the 670 test videos. The number of test pairs is approximately 2 times larger than your  `msvd_captions_test.pkl` in `all` dir, which makes me confused.

I will appreciate that if you can explain how to construct the `msvd_captions_test.pkl` in `all` dir or directly share the code which constructs `msvd_captions_test.pkl` in `all` dir from the original msvd caption annotation file.

Best wishes.

**Comment by niluthpol** [comment]
Thanks for reporting. It seems that the upload was wrong. I uploaded again the pkl files.
