### ISSUE TITLE
Features extraction preprocessing.

### ISSUE THREAD

**Issue by salmon7ish** [niluthpol/multimodal_vtt#22]
Hi. Can you please share code for extracting i3d features or can you tell the exact steps you have used to extract features(from saving images, normalization methods)? I have used online available [code](https://github.com/piergiaj/pytorch-i3d) but it gives me horrible results, whereas if I use your features the results are fine. Thanks in advance.

**Comment by niluthpol** [comment]
I do not remember the steps. However, I am pretty sure I used a different codebase for i3d feature extraction (https://github.com/deepmind/kinetics-i3d) . This is the official codebase. Hope that helps.
