### ISSUE TITLE
train/test data missing on Google Drive

### ISSUE THREAD

**Issue by wingz1** [niluthpol/multimodal_vtt#4]
Hi, thanks for providing this code.   Very interested in this topic area.  I'm trying to run your training script, but it's looking for data that isn't there.  i.e. .../multimodal_vtt/data/msr-vtt/Features/i3d_features/msr_vtt-I3D-RGBFeatures-video8907.npy.   I don't know if there are other missing files since that is where things crash first.   Thanks if you can provide the missing feature file(s)

**Comment by niluthpol** [comment]
Thanks for pointing out. Updated the folder.

**Comment by wingz1** [comment]
There are still more files missing:  multimodal_vtt/data/msr-vtt/Features/i3d_features/msr_vtt-I3D-RGBFeatures-video8160.npy  is the next one I get an error on.
