### ISSUE TITLE
many more feature files missing on Google Drive

### ISSUE THREAD

**Issue by wingz1** [niluthpol/multimodal_vtt#5]
Tried running test_weighted.py several times and it said these were missing.
i3d_features/msr_vtt-I3D-RGBFeatures-video8421.npy
i3d_features/msr_vtt-I3D-RGBFeatures-video8810.npy
i3d_features/msr_vtt-I3D-RGBFeatures-video9289.npy
i3d_features/msr_vtt-I3D-RGBFeatures-video9471.npy
i3d_features/msr_vtt-I3D-RGBFeatures-video9557.npy
I think there are many more missing if you look at the gaps in the numbers in the directory on GoogleDrive.
Thanks!

**Comment by niluthpol** [comment]
Thanks again for reporting the issue. I have uploaded the features again and verified by downloading. I hope the issue is resolved now.
