### ISSUE TITLE
the baseline of VSEPP-ResNet on MSVD

### ISSUE THREAD

**Issue by winnechan** [niluthpol/multimodal_vtt#7]
Hi, I am very interested in your work.

Before dive into your work, I am reproducing the baseline of VSEPP-ResNet on a smaller dataset MSVD, but it's a little bit hard to obtain similar results reported in your work. 

I follows the steps below:
1) extracted features of 25 uniformly sampled frames from ResNet152 and average pooled them
2) create my own dataset class to avoid the same video appear in the same mini-batch
3) using VSEPP code to train on MSVD (1200 for training, 97 for validation), training details as in your work

The results are i2t R@1 13.0 R@5 27.5 R@10 35.1 .

Are there something wrong in my steps? Please help! Thanks!

**Comment by sharontaozi** [comment]
How can you download the msvd?I can't download the videos and captions from msvd
